site_name: SDE Sheet
theme:
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  # logo: 'tuf_logo-removebg-preview.png'
  # favicon: 'favicon.png'
extra:
  social:
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/pavanuppari/
  - icon: fontawesome/brands/github
    link: https://github.com/pavan-uppari
repo_name: pavan-uppari/sde_sheet
repo_url: https://github.com/pavan-uppari/sde_sheet
markdown_extensions:
  - markdown_include.include
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - SDE Sheet:
    - Welcome: index.md
    - Arrays: 
      - Part1: arrays/arrays1.md
      - Part2: arrays/arrays2.md
      - Part3: arrays/arrays3.md
      - Part4: arrays/arrays4.md
    - Linked List:
      - Part1: linked_list/part1.md
      - Part2: linked_list/part2.md
    - Linked List and Arrays: linked_list_and_arrays/linked_list_and_arrays.md
    - Greedy Algorithms: greedy/greedy.md
    - Recursion: recursion/recursion.md
    - Recusion and Backtracking: recursion/backtracking.md
    - Binary Search: binary_search/bs.md
    - Stacks and Queues:
      - Part1: stacks_and_queues/stacks_and_queues_1.md
      - Part2: stacks_and_queues/stacks_and_queues_2.md
    - Binary Trees:
      - Part1: binary_trees/binary_trees.md
      - Part2: binary_trees/binary_trees_2.md
      - Part3: binary_trees/binary_trees_3.md
    - Binary Search Trees:
      - Part1: binary_search_trees/bst.md
      - Part2: binary_search_trees/bst_ii.md
    - DP:
      - Part1: dp/dp_i.md
      - Part2: dp/dp_ii.md